version: '3.9'

services:
  nodejs:
    build: .
    image: backend_node
    ports:
      - '3333:3333'
      - '5555:5555'
    depends_on:
      - postgresql
      - redis
    restart: always
    env_file:
      - .env.docker

  postgresql:
    image: postgres:17
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - polls_pg_data:/var/lib/postgresql/data
    env_file:
      - .env.docker

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - polls_redis_data:/bitnami/redis/data
    env_file:
      - .env.docker

volumes:
  polls_pg_data:
  polls_redis_data:
